search/search/urls.py
from django.conf.urls import patterns, include, url

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    url(r'^admin/doc/', include('django.contrib.admindocs.urls')),
    url(r'^admin/', include(admin.site.urls)),

    url(r'api/v1/', include('web.urls_api', namespace='api')),
    url(r'api/v2/', include('web.urls_api2', namespace='api2')),
    # url(r'dashboard/', include('web.urls_dashboard', namespace='dashboard')),
    url(r'^$', 'web.views.api.index', name='api-root'),
)

search/web/urls.py
from django.conf.urls import patterns, include, url
from .views import api

urlpatterns = patterns('',
	url(r'^providers/(?P<provider>\d+)/courses/$', api.ProviderCourseList.as_view(), name='provider-courses-list'),
	url(r'^providers/(?P<pk>\d+)/$', api.ProviderDetail.as_view(), name='provider-detail'),
	url(r'^providers/$', api.ProviderList.as_view(), name='providers-list'),

	url(r'^courses/stats/$', 'web.views.api.course_stats', name='course-stats'),	
	url(r'^courses/latest/$', api.CourseLatestList.as_view(), name='course-latest'),
	url(r'^courses/view/(?P<linkhash>\w+)/$', api.CourseDetail.as_view(lookup_field='linkhash'), name='course-detail'),
	url(r'^courses/search/$', 'web.views.api.search', name='search-query'),

	url(r'^languages/(?P<language>[\w|\W]+)/courses/$', api.CourseList.as_view(lookup_field='language'), name='language-courses-list'),
	url(r'^languages/$', api.LanguageList.as_view({'get': 'list'}), name='language-list'),

	# url(r'^categories/(?P<category>[\w|\W]+)/(?P<language>[\w|\W]+)/$', views.CourseCategoryList.as_view(), name='category-course-list'),
	url(r'^categories/(?P<category>[\w|\W]+)/$', api.CourseCategoryList.as_view(), name='category-course-list'),
	
	
	url(r'^categories/(?P<language>[\w|\W]+)/$', api.CategoryList.as_view(), name='category-list'),
	url(r'^categories/$', api.CategoryList.as_view(), name='category-list'),
)	

search/data/models.py
from django.db import models
from mptt.models import MPTTModel, TreeForeignKey, TreeManyToManyField
from django.core.urlresolvers import reverse
from django.utils.encoding import force_unicode

import hashlib
import uuid

class Provider(models.Model):
    name = models.CharField(max_length=255)
    external_id = models.TextField(blank=True)
    active = models.BooleanField(default=True)

    def __unicode__(self):
        return self.name

    def get_merlot_count(self):
        return Course.objects.filter(provider=self, merlot_present=True).count()


SOURCE_KIND_CHOICES = (
    ('rss', 'RSS feed'),
    ('scraper', 'Gatherer scraper'),
    ('manual', 'Manual importer'),
    ('form', 'Online form'),
)

class SourceManager(models.Manager):
    def active(self):
        return super(SourceManager, self).get_queryset().filter(disabled=False)

class Source(models.Model):
    provider = models.ForeignKey(Provider)
    kind = models.CharField(choices=SOURCE_KIND_CHOICES, default='rss', max_length=50)
    url  = models.TextField(blank=True, default='')
    update_speed = models.IntegerField(default=0, help_text='Update speed in days, 0 to disable')
    disabled = models.BooleanField(default=False)

    edit_key = models.CharField(max_length=255, blank=True)

    objects = SourceManager()

    def save(self, force_insert=False, force_update=False, using=None):
        if not self.edit_key:
            self.edit_key = uuid.uuid4().get_hex()
        super(Source, self).save(force_insert=force_insert, force_update=force_update, using=using)

    def get_absolute_url(self):
        return reverse('dashboard:source-course-list', kwargs={'pk':self.id})

    def __unicode__(self):
        return u"%s (%s)" % (self.provider.name, self.kind)

    def get_merlot_missing(self):
        return Course.objects.filter(source=self, merlot_present=False).count()

    def get_total_count(self):
        return Course.objects.filter(source=self).count()


CONTENT_MEDIUM_CHOICES = (
    ('text', 'Text'),
    ('textbook', 'Textbook'),
    ('video', 'Video'),
    ('audio', 'Audio')
)

LANGUAGE_CHOICES = (
    ('Catalan', 'Catalan'),
    ('Chinese', 'Chinese'),
    ('Dutch', 'Dutch'),
    ('English', 'English'),
    ('Finnish', 'Finnish'),
    ('French', 'French'),
    ('Galician', 'Galician'),
    ('German', 'German'),
    ('Hebrew', 'Hebrew'),
    ('Indonesian', 'Indonesian'),
    ('Italian', 'Italian'),
    ('Japanese', 'Japanese'),
    ('Korean', 'Korean'),
    ('Malay', 'Malay'),
    ('Persian', 'Persian'),
    ('Polish', 'Polish'),
    ('Portuguese', 'Portuguese'),
    ('Russian', 'Russian'),
    ('Slovenian', 'Slovenian'),
    ('Spanish', 'Spanish'),
    ('Turkish', 'Turkish'),
)

PRIMARY_AUDIENCE_CHOICES = (
    (1, 'Grade School'),
    (2, 'Middle School'),
    (3, 'High School'),
    (4, 'College General Ed'),
    (5, 'College Lower Division'),
    (6, 'College Upper Division'),
    (7, 'Graduate School'),
    (8, 'Professional'),
)

YES_NO_UNSURE_CHOICES = (
    ('Yes', 'Yes'),
    ('No', 'No'),
    ('Unsure', 'Unsure')
)

CC_DERIV_CHOICES = (
    ('Yes', 'Yes'),
    ('No', 'No'),
    ('Sa', 'Share-Alike')
)


class Course(models.Model):
    title = models.TextField()
    linkhash = models.CharField(max_length=96, unique=True)
    linkurl = models.TextField(verbose_name=u'URL')

    provider = models.ForeignKey(Provider, null=True)
    source = models.ForeignKey(Source, null=True)

    description = models.TextField()
    tags = models.TextField(blank=True)

    language = models.CharField(max_length=300, choices=LANGUAGE_CHOICES)
    author = models.CharField(max_length=765, default='')
    author_organization = models.TextField(default='', blank=True)
    rights = models.TextField(default='', blank=True)
    contributors = models.CharField(max_length=765, blank=True, default='')
    license = models.TextField(blank=True, default='')

    date_published = models.DateTimeField(auto_now_add=True)
    date_indexed = models.DateTimeField(auto_now=True)
    date_modified = models.DateTimeField(auto_now=True)

    content_medium = models.CharField(max_length=100, choices=CONTENT_MEDIUM_CHOICES, default='text', verbose_name=u'Content type')

    translated_text = models.TextField(blank=True)
    calais_socialtags = models.TextField(blank=True)
    calais_topics = models.TextField(blank=True)
    opencalais_response = models.TextField(blank=True)

    categories = TreeManyToManyField('Category', blank=True)

    merlot_present = models.BooleanField(default=False)
    merlot_synced = models.BooleanField(default=False)
    merlot_synced_date = models.DateTimeField(null=True)
    merlot_id = models.IntegerField(null=True)
    merlot_ignore = models.BooleanField(default=False)
    merlot_material_type = models.CharField(max_length=100, default='', blank=True)
    merlot_languages = models.ManyToManyField('MerlotLanguage')

    merlot_categories = TreeManyToManyField('MerlotCategory', blank=True)
    merlot_url = models.TextField(blank=True, default='')
    merlot_xml = models.TextField(blank=True, default='')

    image_url = models.TextField(blank=True, default='')
    audience = models.IntegerField(null=True, choices=PRIMARY_AUDIENCE_CHOICES)
    creative_commons = models.CharField(max_length=30, choices=YES_NO_UNSURE_CHOICES, default='Unsure', verbose_name=u'Is CC Licensed?')
    creative_commons_commercial = models.CharField(max_length=30, blank=True, choices=YES_NO_UNSURE_CHOICES, default='',
                                                verbose_name=u'Is CC Commercial allowed?')
    creative_commons_derivatives = models.CharField(max_length=30, blank=True, choices=CC_DERIV_CHOICES, default='',
                                                verbose_name=u'Is CC Derative work allowed or Share-Alike?')

    is_404 = models.BooleanField(default=False)

    @staticmethod
    def calculate_linkhash(linkurl):
        return hashlib.md5(linkurl.encode('utf-8')).hexdigest()

    def save(self, update_linkhash=False, force_insert=False, force_update=False, using=None):
        if not self.linkhash or update_linkhash:
            self.linkhash = self.calculate_linkhash(self.linkurl)

        super(Course, self).save(force_insert=force_insert, force_update=force_update, using=using)

    def get_next(self):
        try:
            return Course.objects.filter(source=self.source, id__gt=self.pk).order_by('id')[0]
        except IndexError:
            pass

    def get_merlot_categories(self):
        paths = []
        for cat in self.merlot_categories.all():
            paths.append(u'/'.join(force_unicode(i) for i in (['All'] + list(cat.get_ancestors()) + [cat])))
        return ';'.join(paths)

    def get_merlot_detail_url(self):
        if self.merlot_id:
            return "http://www.merlot.org/merlot/viewMaterial.htm?id={0}".format(self.merlot_id)

    def is_member(self):
        if self.provider:
            return True

        return False


LOG_STATUS_CHOICES = (
    (0, 'Failed'),
    (1, 'Success')
)


class Log(models.Model):
    source = models.ForeignKey(Source)
    date = models.DateTimeField(auto_now_add=True)
    status = models.IntegerField(default=0)

    processed_courses = models.ManyToManyField(Course, related_name='processed_courses')
    new_courses = models.ManyToManyField(Course, related_name='new_courses')


class Category(MPTTModel):
    name = models.CharField(max_length=50, unique=True)
    parent = TreeForeignKey('self', null=True, blank=True, related_name='children')

    class MPTTMeta:
        order_insertion_by = ['name']

    def __unicode__(self):
        return self.name


class MerlotCategory(MPTTModel):
    name = models.CharField(max_length=150)
    merlot_id = models.IntegerField()
    parent = TreeForeignKey('self', null=True, blank=True, related_name='children')

    class MPTTMeta:
        order_insertion_by = ['name']

    def __unicode__(self):
        return self.name

class SearchQuery(models.Model):
    query = models.TextField()
    language = models.CharField(max_length=150, blank=True)
    count = models.IntegerField(default=1)

    added = models.DateTimeField(auto_now_add=True)
    processed = models.DateTimeField(null=True)

    def __unicode__(self):
        return self.query

class MerlotLanguage(models.Model):
    name = models.CharField(max_length=150)

    def __unicode__(self):
        return self.name

search/web/templates/web/base.html
{% load staticfiles %}<!doctype html>
<html class="no-js" lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
	<title>{% block title %}OCW Courses Data Portal {% endblock %}</title>
	
	<link rel="stylesheet" type="text/css" href="{% static 'foundation/css/foundation.min.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}" />
    <script src="{% static 'foundation/js/vendor/modernizr.js' %}"></script>
	{% block css_head %}{% endblock %}

	<script src="{% static 'foundation/js/vendor/jquery.js' %}"></script>
  	{% block extra_head %}{% endblock %}
</head>
<body>
	{% block headrow %}
	<div class="row" id="top-row">
		<div class="small-4 columns"><img src="{% static 'img/logo.png' %}" alt="OpenCourseWare Consortium logo" /></div>
		<div class="small-3 columns">
			{% if user.is_anonymous %}{% else %}
				Logged in as <b>{{ user.username }}</b> | <a href="{% url 'admin:logout' %}">Logout</a>
			{% endif %}
		</div>		
	</div>
	{% endblock %}

	<div class="main">
		{% block contents %}{% endblock %}
	</div>
    
    <script src="{% static 'foundation/js/foundation.min.js' %}"></script>
	{% block footer_js %}{% endblock %}
	<script src="{% static 'script.js' %}"></script>
</body>
</html>

search/web/templates/web/course_detail.html
{% extends "web/base.html" %}{% load mptt_tags %}

{% block contents %}
<div class="row">
	<div class="small-12 columns">
		<h2><a href="{% url 'dashboard:source-course-list' course.source.id %}">{{ course.provider.name }}</a></h2>
		<h1>{{ course.title }}</h1>
		<dl>
			<dt>Link</dt>
			<dd><a href="{{ course.linkurl }}">{{ course.linkurl }}</a></dd>
			<dt>Author</dt>
			<dd>{{ course.author|default:'N/A' }}</dd>
			<dt>Description</dt>
			<dd>{{ course.description|default:'N/A' }}</dd>
			<dt>Tags</dt>
			<dd>{{ course.tags|default:'N/A' }}</dd>
			<dt>Language</dt>
			<dd>{{ course.language|default:'N/A' }}</dd>
			<dt>Categories</dt>
			{% if course.categories.all %}
				<dd>{{ course.categories.all|join:', ' }}</dd>
			{% else %}
				<dd>N/A</dd>
			{% endif %}
			<dt>MERLOT Categories</dt>
			{% if course.merlot_categories.all %}
				<dd>
					{% for node in course.merlot_categories.all %}
						{{ node.get_ancestors|tree_path:" > " }} > {{ node }}<br />
					{% endfor %}
				</dd>
			{% else %}
				<dd>N/A</dd>
			{% endif %}			
			<dt>Published</dt>
			<dd>{{ course.date_published }}</dd>
			<dt>Content Medium</dt>
			<dd>{{ course.get_content_medium_display }}</dd>
			<dt>Image URL</dt>
			<dd>{{ course.image_url }}</dd>
			<dt>Audience</dt>
			<dd>{{ course.get_audience_display }}</dd>
			<dt>Creative Commons</dt>
			<dd>{{ course.get_creative_commons_display }}</dd>
			<dt>Creative Commons Commercial use allowed</dt>
			<dd>{{ course.get_creative_commons_commercial_display }}</dd>
			<dt>Creative Commons Derivates allowed</dt>
			<dd>{{ course.get_creative_commons_derivatives_display }}</dd>
		</dl>
	</div>

<div class="row">
	<div class="small-3 columns">
		<a href="{% url 'dashboard:course-edit' course.id %}" class="button small">Edit</a>
	</div>
	{% if course.get_next %}
		<div class="small-3 columns right">
			<a href="{% url 'dashboard:course-view' linkhash=course.get_next.linkhash %}" class="button small">Next</a>
		</div>
	{% endif %}
</div>
{% endblock %}

search/web/templates/web/course_form.html
{% extends "web/base.html" %}{% load crispy_forms_tags django_select2_tags staticfiles %}

{% block css_head %}
	{% import_django_select2_css 1 %}
	<style type="text/css" src="{% static 'select2-foundation5.css' %}"></style>
{% endblock %}
{% block footer_js %}{% import_django_select2_js 1 %}{% endblock %}

{% block contents %}



<div class="row">
	<h2>Add new Course to <strong>{{ source.provider.name }}</strong></h2>

	<div class="small-10 columns">
		{{ form.non_field_errors }}
		{% crispy form %}
	</div>
</div>
<div class="row">
	<div style="height: 300px;"></div>
</div>
{% endblock %}

search/web/templates/web/source_course_list.html
{% extends "web/base.html" %}

{% block contents %}
<div class="row">
	<div class="small-12 columns">
		<h1>List of courses at {{ source.provider.name }}</h1>
		<table>
			<thead>
				<tr>
					<th>Merlot</th>
					<th>Title</th>
					<th>Author</th>
					<th>Language</th>
				</tr>
			</thead>
			<tbody>
				{% for course in object_list %}
				<tr>
					{% if course.merlot_ignore %}
						<td>ign</td>
					{% elif course.merlot_present %}
						<td>pre</td>
					{% elif course.merlot_synced %}
						<td>sync</td>
					{% else %}
						{% if course.merlot_categories.count %}
							<td><a href="{% url 'dashboard:course-edit' course.id %}" class="button tiny" style="margin-bottom: 0;">edit</a></td>
						{% else %}
							<td><a href="{% url 'dashboard:course-edit' course.id %}" class="button alert tiny" style="margin-bottom: 0;">edit</a></td>
						{% endif %}
					{% endif %}
					<td><a href="{% url 'dashboard:course-view' linkhash=course.linkhash %}">{{ course.title }}</a></td>
					<td>{{ course.author }}</td>
					<td>{{ course.language }}</td>
				</tr>
				{% endfor %}
			</tbody>
		</table>
	</div>
</div>
{% if source.kind == 'form' %}
	<div class="row">
		<div class="small-6 columns">
			<a href="{% url 'dashboard:course-add' edit_key=source.edit_key %}" class="button small">Add a Course</a>
		</div>
	</div>
{% endif %}
{% endblock %}